'use client';

import { useEffect, useState } from 'react';
import { Loader2, Upload, UserPlus } from 'lucide-react';
import { useToast } from '../../context/ToastContext';

const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL || 'http://localhost:8000';

export default function UserProvisioning({ mode = 'faculty' }) {
  const { showToast } = useToast();
  const [departments, setDepartments] = useState([]);
  const [loadingDepartments, setLoadingDepartments] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [csvFile, setCsvFile] = useState(null);
  const [result, setResult] = useState(null);
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    department_id: '',
    role: mode === 'hod' ? 'HOD' : 'FACULTY',
  });

  const isStudentMode = mode === 'students';
  const roleLabel = mode === 'hod' ? 'HOD' : 'Faculty';

  useEffect(() => {
    const fetchDepartments = async () => {
      try {
        setLoadingDepartments(true);
        const response = await fetch(`${API_BASE_URL}/auth/departments`);
        const payload = await response.json();
        if (!response.ok) throw new Error(payload.detail || 'Failed to load departments');
        setDepartments(payload.data || []);
      } catch (error) {
        showToast(error.message, 'error');
      } finally {
        setLoadingDepartments(false);
      }
    };
    fetchDepartments();
  }, [showToast]);

  const handleCreateUser = async (e) => {
    e.preventDefault();
    try {
      setSubmitting(true);
      const token = localStorage.getItem('authToken') || '';
      const response = await fetch(`${API_BASE_URL}/auth/coordinator/users`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify(formData),
      });
      const payload = await response.json();
      if (!response.ok) throw new Error(payload.detail || 'Failed to create user');
      showToast(payload.message || `${roleLabel} created successfully`, 'success');
      setResult(payload.data || null);
      setFormData((prev) => ({ ...prev, name: '', email: '' }));
    } catch (error) {
      showToast(error.message, 'error');
    } finally {
      setSubmitting(false);
    }
  };

  const handleUploadStudents = async () => {
    if (!csvFile) {
      showToast('Select a CSV file first.', 'error');
      return;
    }
    try {
      setUploading(true);
      const token = localStorage.getItem('authToken') || '';
      const form = new FormData();
      form.append('file', csvFile);
      const response = await fetch(`${API_BASE_URL}/auth/coordinator/students/upload`, {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${token}`,
        },
        body: form,
      });
      const payload = await response.json();
      if (!response.ok) throw new Error(payload.detail || 'Failed to upload students');
      setResult(payload.data || null);
      showToast(payload.message || 'Students uploaded successfully', 'success');
      setCsvFile(null);
    } catch (error) {
      showToast(error.message, 'error');
    } finally {
      setUploading(false);
    }
  };

  if (loadingDepartments) {
    return (
      <div className="p-8 flex items-center justify-center text-gray-400">
        <Loader2 className="w-5 h-5 animate-spin mr-2" />
        Loading provisioning tools...
      </div>
    );
  }

  return (
    <div className="p-6 max-w-4xl mx-auto space-y-6">
      <div>
        <h2 className="text-2xl font-bold text-white">
          {isStudentMode ? 'Student CSV Upload' : `Add ${roleLabel}`}
        </h2>
        <p className="text-sm text-gray-400 mt-1">
          {isStudentMode
            ? 'CSV columns: name, email, prn, department_id, division. Password is set to PRN.'
            : `Create ${roleLabel} account with autogenerated password and email credentials.`}
        </p>
      </div>

      {isStudentMode ? (
        <div className="bg-gray-900/50 border border-gray-800 rounded-xl p-6 space-y-4">
          <input
            type="file"
            accept=".csv"
            onChange={(e) => setCsvFile(e.target.files?.[0] || null)}
            className="w-full bg-gray-950 border border-gray-700 rounded-lg px-4 py-2 text-white"
          />
          <button
            type="button"
            onClick={handleUploadStudents}
            disabled={uploading || !csvFile}
            className="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white font-medium disabled:opacity-50"
          >
            {uploading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Upload className="w-4 h-4" />}
            {uploading ? 'Uploading...' : 'Upload Students'}
          </button>
        </div>
      ) : (
        <form onSubmit={handleCreateUser} className="bg-gray-900/50 border border-gray-800 rounded-xl p-6 grid grid-cols-1 md:grid-cols-2 gap-4">
          <input
            type="text"
            placeholder="Full name"
            value={formData.name}
            onChange={(e) => setFormData((prev) => ({ ...prev, name: e.target.value }))}
            required
            className="bg-gray-950 border border-gray-700 rounded-lg px-4 py-2.5 text-white"
          />
          <input
            type="email"
            placeholder="Email"
            value={formData.email}
            onChange={(e) => setFormData((prev) => ({ ...prev, email: e.target.value }))}
            required
            className="bg-gray-950 border border-gray-700 rounded-lg px-4 py-2.5 text-white"
          />
          <select
            value={formData.department_id}
            onChange={(e) => setFormData((prev) => ({ ...prev, department_id: e.target.value }))}
            required
            className="bg-gray-950 border border-gray-700 rounded-lg px-4 py-2.5 text-white"
          >
            <option value="">Select Department</option>
            {departments.map((dept) => (
              <option key={dept.department_id} value={dept.department_id}>
                {dept.department_name}
              </option>
            ))}
          </select>
          <select
            value={formData.role}
            onChange={(e) => setFormData((prev) => ({ ...prev, role: e.target.value }))}
            required
            className="bg-gray-950 border border-gray-700 rounded-lg px-4 py-2.5 text-white"
          >
            <option value="FACULTY">FACULTY</option>
            <option value="HOD">HOD</option>
          </select>
          <div className="md:col-span-2">
            <button
              type="submit"
              disabled={submitting}
              className="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white font-medium disabled:opacity-50"
            >
              {submitting ? <Loader2 className="w-4 h-4 animate-spin" /> : <UserPlus className="w-4 h-4" />}
              {submitting ? 'Creating...' : `Create ${roleLabel}`}
            </button>
          </div>
        </form>
      )}

      {result ? (
        <div className="bg-gray-900/50 border border-gray-700 rounded-xl p-4 text-sm text-gray-200">
          <pre className="whitespace-pre-wrap">{JSON.stringify(result, null, 2)}</pre>
        </div>
      ) : null}
    </div>
  );
}
